const config = {
  API_KEY: process.env.GOV_API_KEY,
};

import express from "express";

const fake = {
  data: [
    {
      record_date: "1993-05-11",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4241563251233.22",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "11",
    },
    {
      record_date: "1993-05-12",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4245569745868.36",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "12",
    },
    {
      record_date: "1993-05-13",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4247268504239.08",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "13",
    },
    {
      record_date: "1993-05-14",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4247908515485.90",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "14",
    },
    {
      record_date: "1993-05-17",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4282840338892.20",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "17",
    },
    {
      record_date: "1993-05-18",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4284319830220.98",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "18",
    },
    {
      record_date: "1993-05-19",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4285942530790.21",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "19",
    },
    {
      record_date: "1993-05-20",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4287296327978.00",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "20",
    },
    {
      record_date: "1993-05-21",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4287849937583.96",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "21",
    },
    {
      record_date: "1993-05-24",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4289248864590.92",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "24",
    },
    {
      record_date: "1993-05-25",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4289997991055.52",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "25",
    },
    {
      record_date: "1993-05-26",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4293295034918.79",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "26",
    },
    {
      record_date: "1993-05-27",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4295640444150.75",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "27",
    },
    {
      record_date: "1993-05-28",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4296278014612.43",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "05",
      record_calendar_day: "28",
    },
    {
      record_date: "1993-06-01",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4304846924516.35",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "01",
    },
    {
      record_date: "1993-06-02",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4301597684725.47",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "02",
    },
    {
      record_date: "1993-06-03",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4294168230173.50",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "03",
    },
    {
      record_date: "1993-06-04",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4301347713341.66",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "04",
    },
    {
      record_date: "1993-06-07",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4301281229791.00",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "07",
    },
    {
      record_date: "1993-06-08",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4303726252363.71",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "08",
    },
    {
      record_date: "1993-06-09",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4300363069605.66",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "09",
    },
    {
      record_date: "1993-06-10",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4298707666818.39",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "10",
    },
    {
      record_date: "1993-06-11",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4300437428305.74",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "11",
    },
    {
      record_date: "1993-06-14",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4301108267950.79",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "14",
    },
    {
      record_date: "1993-06-15",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4301302751632.55",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "15",
    },
    {
      record_date: "1993-06-16",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4302702770198.75",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "16",
    },
    {
      record_date: "1993-06-17",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4296788021011.13",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "17",
    },
    {
      record_date: "1993-06-18",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4296985941229.90",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "18",
    },
    {
      record_date: "1993-06-21",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4298022359229.61",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "21",
    },
    {
      record_date: "1993-06-22",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4299889449998.07",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "22",
    },
    {
      record_date: "1993-06-23",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4302429272488.54",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "23",
    },
    {
      record_date: "1993-06-24",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4304357332097.66",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "24",
    },
    {
      record_date: "1993-06-25",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4305268550989.52",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "25",
    },
    {
      record_date: "1993-06-28",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4308429367169.37",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "28",
    },
    {
      record_date: "1993-06-29",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4309613793364.13",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "29",
    },
    {
      record_date: "1993-06-30",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4351950333834.76",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "3",
      record_calendar_year: "1993",
      record_calendar_quarter: "2",
      record_calendar_month: "06",
      record_calendar_day: "30",
    },
    {
      record_date: "1993-07-01",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4346364235426.75",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "01",
    },
    {
      record_date: "1993-07-02",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4336425589564.94",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "02",
    },
    {
      record_date: "1993-07-06",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4337115603632.49",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "06",
    },
    {
      record_date: "1993-07-07",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4337775212166.64",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "07",
    },
    {
      record_date: "1993-07-08",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4340814508845.90",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "08",
    },
    {
      record_date: "1993-07-09",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4336575146686.68",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "09",
    },
    {
      record_date: "1993-07-12",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4333686507733.04",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "12",
    },
    {
      record_date: "1993-07-13",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4335589907030.89",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "13",
    },
    {
      record_date: "1993-07-14",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4336911526100.26",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "14",
    },
    {
      record_date: "1993-07-15",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4333088457842.09",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "15",
    },
    {
      record_date: "1993-07-16",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4334092903543.66",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "16",
    },
    {
      record_date: "1993-07-19",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4334398784435.69",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "19",
    },
    {
      record_date: "1993-07-20",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4335488071744.30",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "20",
    },
    {
      record_date: "1993-07-21",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4336608558720.53",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "21",
    },
    {
      record_date: "1993-07-22",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4340981032082.67",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "22",
    },
    {
      record_date: "1993-07-23",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4342543241528.91",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "23",
    },
    {
      record_date: "1993-07-26",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4343781271134.35",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "26",
    },
    {
      record_date: "1993-07-27",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4346077874112.13",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "27",
    },
    {
      record_date: "1993-07-28",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4348145703496.26",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "28",
    },
    {
      record_date: "1993-07-29",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4352487844872.15",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "29",
    },
    {
      record_date: "1993-07-30",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4350260845100.30",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "07",
      record_calendar_day: "30",
    },
    {
      record_date: "1993-08-02",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4360010907754.76",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "02",
    },
    {
      record_date: "1993-08-03",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4352794596878.03",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "03",
    },
    {
      record_date: "1993-08-04",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4355231149967.19",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "04",
    },
    {
      record_date: "1993-08-05",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4359518864582.46",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "05",
    },
    {
      record_date: "1993-08-06",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4355101320997.57",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "06",
    },
    {
      record_date: "1993-08-09",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4351854475662.86",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "09",
    },
    {
      record_date: "1993-08-10",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4353854475662.86",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "10",
    },
    {
      record_date: "1993-08-11",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4355722017571.74",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "11",
    },
    {
      record_date: "1993-08-12",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4359136129737.25",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "12",
    },
    {
      record_date: "1993-08-13",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4359628169239.52",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "13",
    },
    {
      record_date: "1993-08-16",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4374900792622.60",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "16",
    },
    {
      record_date: "1993-08-17",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4375854177681.80",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "17",
    },
    {
      record_date: "1993-08-18",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4376450226589.55",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "18",
    },
    {
      record_date: "1993-08-19",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4377925283974.00",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "19",
    },
    {
      record_date: "1993-08-20",
      debt_held_public_amt: "null",
      intragov_hold_amt: "null",
      tot_pub_debt_out_amt: "4378964399702.83",
      src_line_nbr: "1",
      record_fiscal_year: "1993",
      record_fiscal_quarter: "4",
      record_calendar_year: "1993",
      record_calendar_quarter: "3",
      record_calendar_month: "08",
      record_calendar_day: "20",
    },
  ],
  meta: {
    count: 100,
    labels: {
      record_date: "Record Date",
      debt_held_public_amt: "Debt Held by the Public",
      intragov_hold_amt: "Intragovernmental Holdings",
      tot_pub_debt_out_amt: "Total Public Debt Outstanding",
      src_line_nbr: "Source Line Number",
      record_fiscal_year: "Fiscal Year",
      record_fiscal_quarter: "Fiscal Quarter Number",
      record_calendar_year: "Calendar Year",
      record_calendar_quarter: "Calendar Quarter Number",
      record_calendar_month: "Calendar Month Number",
      record_calendar_day: "Calendar Day Number",
    },
    dataTypes: {
      record_date: "DATE",
      debt_held_public_amt: "CURRENCY",
      intragov_hold_amt: "CURRENCY",
      tot_pub_debt_out_amt: "CURRENCY",
      src_line_nbr: "INTEGER",
      record_fiscal_year: "YEAR",
      record_fiscal_quarter: "QUARTER",
      record_calendar_year: "YEAR",
      record_calendar_quarter: "QUARTER",
      record_calendar_month: "MONTH",
      record_calendar_day: "DAY",
    },
    dataFormats: {
      record_date: "YYYY-MM-DD",
      debt_held_public_amt: "$10.20",
      intragov_hold_amt: "$10.20",
      tot_pub_debt_out_amt: "$10.20",
      src_line_nbr: "10",
      record_fiscal_year: "YYYY",
      record_fiscal_quarter: "Q",
      record_calendar_year: "YYYY",
      record_calendar_quarter: "Q",
      record_calendar_month: "MM",
      record_calendar_day: "DD",
    },
    "total-count": 7852,
    "total-pages": 79,
  },
};
const router = express.Router();

/**
 *
 * 1. Fetch data from the API + return it
 * 2. Fetch data + save copy to the database
 * 3. Fetch data from database + return it
 * 4. Fetch data from database + fetch data from API + compare + return it
 * */
router.get("/debt_to_penny", async (req, res) => {
  // const response = await fetch(
  //   `https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v2/accounting/od/debt_to_penny`
  // );
  // type baseType = {
  //   data: unknown[];
  //   meta: {
  //     labels: Record<string, string>;
  //     datatypes: Record<string, string>;
  //     dataFormats: Record<string, string>;
  //     count: number;
  //     "total-count": number;
  //     "total-pages": number;
  //   };
  // };

  // const data: baseType = await response.json();
  const data = fake;

  type returnType = {
    message: string;
    payload: {
      data: unknown[];
      meta: unknown;
      columns: Array<{
        label: string;
        format: string;
        type: string;
        field: string;
      }>;
    };
  };

  const returnPayload: returnType = {
    message: "success",
    payload: {
      data: data.data,
      meta: data.meta,
      columns: Object.keys(data.meta.dataTypes as Record<string, string>).map(
        (key) => {
          return {
            label: data.meta.labels[key],
            format: data.meta.dataFormats[key],
            type: data.meta.dataTypes[key],
            field: key,
          };
        }
      ),
    },
  };

  return res.json(returnPayload);
});

export default router;
